server:
  port: 8082 # 服务端口
  ip-server: 81.68.82.195

spring:
  datasource: # mysql数据库连接
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${server.ip-server}:3306/ris_db?serverTimezone=GMT%2B8&characterEncoding=utf-8
      username: root
      password: mbsh089668
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${server.ip-server}:3307/ris_db?serverTimezone=GMT%2B8&characterEncoding=utf-8
      username: root
      password: 123456
  redis:
    host: ${server.ip-server}
    port: 6379
    database: 0
    password: mbsh089668 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

mock:
  token: 1234
